### ISSUE TITLE
Feature Request: Add Filter / Exclude Field Names / Types

### ISSUE THREAD

**Issue by ERobishaw** [rvegajr/ez-db-codegen-core#4]
**Would be great to be able to exclude certain fields From Tables**
**Also:** Support WildCards and FieldType
1) **Globally** (all Table) (ex: GlobalExcludeFields: ["\*_Temp", "\*_OtherBitField(bit)", "\*(Geography)"]
   Above would ignore: 
- all fields with the word '_Temp', 
-  all bit fields with the name '_OtherBitField', 
- any Geography Field
2) **Or Per Table** {Table: "Products", ExcludeFields: ["SomeField", "\*_Temp"]}

**Comment by rvegajr** [comment]
completed
